name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # TODO(map) Figure out how to customize mypy so I don't get as many errors.
      # - name: Lint with mypy
      #   run: |
      #     mypy --strict katana/katana.py
      - name: Test with pytest
        run: |
          pytest tests
